//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contains
    {
        public int termId { get; set; }
        public int documentId { get; set; }
        public long positionIndex { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Terms Terms { get; set; }
    }
}
